# Generated by Django 5.0.2 on 2024-02-21 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemType',
            fields=[
                ('menuItemTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('menuItemType', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='itemType',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.menuitemtype'),
        ),
    ]
