# Generated by Django 5.0.2 on 2024-02-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menuitemtype_menuitem_itemtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isPending',
            field=models.BooleanField(default=True),
        ),
    ]
